# Site settings
title: ComaWorld Contents
email: coma333ryu@gmail.com

description: "Welcome to the Coma World !!!"
baseurl: ""

# url: "http://yourdomain.com"

twitter_username: Coma333
github_username: coma333ryu
facebook_username: jeongbu.yun

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
lsi: false
excerpt_separator: "\n\n"

kramdown:
  auto_ids: true
  input: GFM
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

redcarpet:
    extensions:
      - no_intra_emphasis
      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap

safe: true
highlighter: pygments
lsi: false

permalink: pretty

paginate: 5
paginate_path: "/types/:num"

gems:
  - jekyll-redirect-from
  - jemoji